[profile.release]
overflow-checks = true

[workspace]
resolver = "2"
members = [ "crates/common", "crates/delegator", "crates/executor", "crates/peer" , "crates/prover"]
exclude = []

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/iosis-tech/sharp-p2p"
license-file = "LICENSE"

[workspace.dependencies]
async-process = "2.2.0"
tokio = { version = "1.36", features = ["full"] }
libp2p = { version = "0.53.2", features = [ "tokio", "gossipsub", "kad", "mdns", "noise", "macros", "tcp", "yamux", "quic"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "1.0.58"
futures = "0.3.30"
hex = "0.4.3"

sharp-p2p-delegator = { path = "crates/delegator" }
sharp-p2p-executor = { path = "crates/executor" }
sharp-p2p-prover = { path = "crates/prover" }
sharp-p2p-common = { path = "crates/common" }