[package]
name = "sharp-p2p-common"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-felt.workspace = true
hex.workspace = true
num-bigint.workspace = true
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true