---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docs-zetina-cert
spec:
  secretName: docs-zetina-tls

  dnsNames:
    - docs.zetina.iosis.tech
  issuerRef:
    name: letsencrypt-http01
    kind: Issuer