apiVersion: skaffold/v4beta3
kind: Config
build:
  artifacts:
  - image: registry.internal.iosis.tech/zetina-docs
    docker:
      dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - ./k8s