name: Continuous Integration - tests

on:
  push:
  pull_request:

jobs:
  formatting-and-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v3
    
      - name: Format code
        run: cargo fmt --check
      
      - name: Run cargo tests
        run: cargo test
    
      - name: Run snforge tests
        run: snforge test